### ISSUE TITLE
Icons lack color

### ISSUE THREAD

**Issue by aalvarado** [donkeystep/jira-dark#3]
Icons on the side of the board on agile are svg and lack color.

**Comment by sergey124** [comment]
I'm sorry for not noticing the issue.
Fixed in #7 

@aalvarado , could you please confirm it's fixed?
Link to style: https://userstyles.org/styles/116696/jira-dark-nightshift-eye-care-based

**Comment by sergey124** [comment]
Fixed in #7
Closing as duplicate.

**Comment by aalvarado** [comment]
Unfortunately I'm not using stylish anymore, switched to stylebot. sorry

**Comment by sergey124** [comment]
Huh, interesting, I have it installed, too) 

Though, I use stylebot for quick page modifications, like make larger/smaller or hide element.
And Stylish - for managing themes for all the internet (including this great style for Github: https://userstyles.org/styles/37035/github-dark ).

Stylish maintainer changed recently, and it's in active development. Which means bugs and unwanted features, unfortunately. But I think that'll get better soon, they have 
Trello: https://trello.com/b/xzSUbdNv/stylish-features-list
and Github: https://github.com/stylish-userstyles/stylish-chrome
